---

- name: update skel files
  copy:
    src: "{{ item[0] }}"
    dest: "{{ item[1].dest }}"
    owner: "{{ item[1].owner }}"
    group: "{{ item[1].owner }}"
    mode: "{{ item[1].mode }}"
  loop: "{{ skel_dot_profile_files | product(skel_dot_profile_dests) | list }}"

- name: update root .profile
  lineinfile:
    path: "{{ item[0] }}"
    insertafter: EOF
    line: "{{ item[1] }}"
  loop: "{{ skel_root_dot_profile_files | product(skel_root_dot_profile_lines) | list }}"

- name: update root .gitconfig
  template:
    src: root/.gitconfig.j2
    dest: /root/.gitconfig
    owner: root
    group: root
    mode: "0600"
