---

dependency:
  name: 'galaxy'

driver:
  name: 'vagrant'
  provider:
    name: 'virtualbox'

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: 'Debian'
    box: 'generic/debian10'

  - name: 'OpenBSD'
    box: 'generic/openbsd6'
    boot_timeout: 600

provisioner:
  name: 'ansible'
  config_options:
    defaults:
      stdout_callback: 'yaml'
      bin_ansible_callbacks: True
  options:
    D: True
  log: True

verifier:
  name: 'ansible'
