---

name: linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: YAML Linter
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: "."

      - name: Ansible Linter
        uses: ansible/ansible-lint-action@master
        with:
          targets: "."
          override-deps: |
            ansible==2.9
